// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromoCodeManagementSystem.Context;

#nullable disable

namespace PromoCodeManagementSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220327034906_DBInit")]
    partial class DBInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PromoCodeManagementSystem.Models.PromocodesModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("char(37)");

                    b.Property<DateTime>("createdDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("phoneNo")
                        .HasColumnType("longtext");

                    b.Property<string>("promocode")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("updatedDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("id")
                        .HasName("PK_Promocodes");

                    b.ToTable("Promocodes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
